### ISSUE TITLE
Seems IceTransports constraint breaks Chrome Beta build

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/webrtcomm#40]
Seems iceTransports  constraint is no longer valid.

```
WebRTCommCall:open():calleePhoneNumber=+1234
WebRTCommCall:open():configuration={"displayName":"Alice Alissys","localMediaStream":{},"audioMediaFlag":true,"videoMediaFlag":false,"messageMediaFlag":false,"audioCodecsFilter":"","videoCodecsFilter":""}
WebRTCommCall:checkConfiguration()
PrivateJainSipCallConnector:open()
PrivateJainSipCallConnector:checkConfiguration()
WebRTCommCall:createPeerConnection()
WebRTCommCall:createPeerConnection():rtcPeerConnectionConfiguration={"iceServers":[{"url":"stun:stun.l.google.com:19302"}]}
WebRTCommCall:createPeerConnection():peerConnectionConstraints=undefined
Unknown constraint named IceTransports rejected
WebRTCommCall:open(): catched exception:NotSupportedError: Failed to construct 'RTCPeerConnection': Unsatisfiable constraint IceTransports
WebRTCommCall:close(), with no media stats
WebRTCommCall:hangup()
PrivateJainSipCallConnector:close(): this.sipCallState=INVITING_INITIAL_STATE
PrivateJainSipCallConnector:resetSipContext()
PrivateJainSipClientConnector:removeSessionConnector(): sipSessionId=1460206588906
WebRTCommCall:onPrivateCallConnectorCallClosedEvent()
WebRTCommClient:call(): catched exception:NotSupportedError: Failed to construct 'RTCPeerConnection': Unsatisfiable constraint IceTransports
Error: Failed to construct 'RTCPeerConnection': Unsatisfiable constraint IceTransports
    at Error (native)
    at new window.RTCPeerConnection (https://tadhack.restcomm.com/olympus/resources/js/adapter/adapter.js:259:14)
    at WebRTCommCall.createRTCPeerConnection (https://tadhack.restcomm.com/olympus/resources/js/mobicents-libs/WebRTComm.js:2999:25)
    at WebRTCommCall.open (https://tadhack.restcomm.com/olympus/resources/js/mobicents-libs/WebRTComm.js:2070:12)
    at WebRTCommClient.call (https://tadhack.restcomm.com/olympus/resources/js/mobicents-libs/WebRTComm.js:4695:22)
    at Scope.$scope.makeCall (https://tadhack.restcomm.com/olympus/resources/js/controllers/room.js:272:41)
    at https://tadhack.restcomm.com/olympus/resources/js/controllers/room.js:258:46
    at Object.fn (https://tadhack.restcomm.com/olympus/resources/js/controllers/room.js:249:11)
    at Scope.$digest (https://tadhack.restcomm.com/olympus/lib/angular/angular.js:14230:29)
    at Scope.$apply (https://tadhack.restcomm.com/olympus/lib/angular/angular.js:14493:24)
TypeError: Cannot read property 'calleePhoneNumber' of undefined
    at room.js:402
    at Scope.$eval (angular.js:14388)
    at Scope.$apply (angular.js:14487)
    at room.js:400
    at Scope.$broadcast (angular.js:14707)
    at onWebRTCommCallOpenErrorEvent (services.js:46)
    at WebRTComm.js:2137
```

**Comment by atsakiridis** [comment]
Turns out this has been moved to [RTCConfiguration](http://w3c.github.io/webrtc-pc/#idl-def-RTCConfiguration) used in PeerConnection constructor and seems to be supported both in Chrome and Firefox. That said together with this fix let's remove the browser-dependent code when creating PeerConnection
