### ISSUE TITLE
Fix issue with bad PeerConnection state

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/webrtcomm#63]
```
2016-17-11 14:00:44.246 WebRTCommCall:onRtcPeerConnectionIceCandidateEvent(): RTCPeerConnection bad state!offer-sent 

Stack trace: 
    at commonLog (https://cloud.restcomm.com/olympus/resources/js/mobicents-libs/WebRTComm.js:4884:10)
    at Object.console.error (https://cloud.restcomm.com/olympus/resources/js/mobicents-libs/WebRTComm.js:4957:4)
    at WebRTCommCall.onRtcPeerConnectionIceCandidateEvent (https://cloud.restcomm.com/olympus/resources/js/mobicents-libs/WebRTComm.js:3418:15)
    at RTCPeerConnection.peerConnection.onicecandidate (https://cloud.restcomm.com/olympus/resources/js/mobicents-libs/WebRTComm.js:3033:8)
```

Here's the full [web console](https://gist.github.com/atsakiridis/3c833c60608ac767ea5de110df90e5c4)

Notice that this doesn't seem to have any side effects in the calls but still messes up with our logs

**Comment by atsakiridis** [comment]
This turned out to be pretty nasty. Some details:
- Reason this seems to happen is that jain sip invite/accept are called in two places within WebRTCommCall.js. Once in `onRtcPeerConnectionIceCandidateEvent` and once in `onRtcPeerConnectionGatheringChangeEvent`. Notice that `onRtcPeerConnectionIceCandidateEvent` gets called multiple times, which makes it even worse.
- Normally this should only occur in `onRtcPeerConnectionGatheringChangeEvent` when gathering state is `complete` (which is what we do for the mobile SDKs). So I tried to fix that, but it turns out that if I do that ice gathering state never transitions to `complete`
- I'm guessing there's a problem with STUN/TURN servers not being properly setup for PC and this causes processing to get stuck on `gathering`

That said, best course of action would be to refactor the STUN/TURN server handling so that we use xirsys, as we do with iOS/Android, and probably make that configurable too. After that I think it should work.

**Comment by atsakiridis** [comment]
Turns out that `onicegatheringchange` is not supported for chrome (even though the native code used by our mobile SDKs exposes that just fine and it is part of the [spec](http://w3c.github.io/webrtc-pc/#event-icegatheringstatechange)). So the way to do that for the web is to listen to `onicecandidate` when the candidate is null.

For more info refer to [this](https://bugs.chromium.org/p/webrtc/issues/detail?id=1393) and [this](https://groups.google.com/forum/#!topic/discuss-webrtc/3L11ZWtqo3Y)

**Comment by atsakiridis** [comment]
Testing @ipsilantide gmail filters

**Comment by atsakiridis** [comment]
Testing despina's gmail filters without mention
